@[Link("GLU")]
lib LibGLU
  EXT_OBJECT_SPACE_TESS       =       1
  EXT_NURBS_TESSELLATOR       =       1
  FALSE                       =       0
  TRUE                        =       1
  VERSION_1_1                 =       1
  VERSION_1_2                 =       1
  VERSION_1_3                 =       1
  VERSION                     =  100800
  EXTENSIONS                  =  100801
  INVALID_ENUM                =  100900
  INVALID_VALUE               =  100901
  OUT_OF_MEMORY               =  100902
  INCOMPATIBLE_GL_VERSION     =  100903
  INVALID_OPERATION           =  100904
  OUTLINE_POLYGON             =  100240
  OUTLINE_PATCH               =  100241
  NURBS_ERROR                 =  100103
  ERROR                       =  100103
  NURBS_BEGIN                 =  100164
  NURBS_BEGIN_EXT             =  100164
  NURBS_VERTEX                =  100165
  NURBS_VERTEX_EXT            =  100165
  NURBS_NORMAL                =  100166
  NURBS_NORMAL_EXT            =  100166
  NURBS_COLOR                 =  100167
  NURBS_COLOR_EXT             =  100167
  NURBS_TEXTURE_COORD         =  100168
  NURBS_TEX_COORD_EXT         =  100168
  NURBS_END                   =  100169
  NURBS_END_EXT               =  100169
  NURBS_BEGIN_DATA            =  100170
  NURBS_BEGIN_DATA_EXT        =  100170
  NURBS_VERTEX_DATA           =  100171
  NURBS_VERTEX_DATA_EXT       =  100171
  NURBS_NORMAL_DATA           =  100172
  NURBS_NORMAL_DATA_EXT       =  100172
  NURBS_COLOR_DATA            =  100173
  NURBS_COLOR_DATA_EXT        =  100173
  NURBS_TEXTURE_COORD_DATA    =  100174
  NURBS_TEX_COORD_DATA_EXT    =  100174
  NURBS_END_DATA              =  100175
  NURBS_END_DATA_EXT          =  100175
  NURBS_ERROR1                =  100251
  NURBS_ERROR2                =  100252
  NURBS_ERROR3                =  100253
  NURBS_ERROR4                =  100254
  NURBS_ERROR5                =  100255
  NURBS_ERROR6                =  100256
  NURBS_ERROR7                =  100257
  NURBS_ERROR8                =  100258
  NURBS_ERROR9                =  100259
  NURBS_ERROR10               =  100260
  NURBS_ERROR11               =  100261
  NURBS_ERROR12               =  100262
  NURBS_ERROR13               =  100263
  NURBS_ERROR14               =  100264
  NURBS_ERROR15               =  100265
  NURBS_ERROR16               =  100266
  NURBS_ERROR17               =  100267
  NURBS_ERROR18               =  100268
  NURBS_ERROR19               =  100269
  NURBS_ERROR20               =  100270
  NURBS_ERROR21               =  100271
  NURBS_ERROR22               =  100272
  NURBS_ERROR23               =  100273
  NURBS_ERROR24               =  100274
  NURBS_ERROR25               =  100275
  NURBS_ERROR26               =  100276
  NURBS_ERROR27               =  100277
  NURBS_ERROR28               =  100278
  NURBS_ERROR29               =  100279
  NURBS_ERROR30               =  100280
  NURBS_ERROR31               =  100281
  NURBS_ERROR32               =  100282
  NURBS_ERROR33               =  100283
  NURBS_ERROR34               =  100284
  NURBS_ERROR35               =  100285
  NURBS_ERROR36               =  100286
  NURBS_ERROR37               =  100287
  AUTO_LOAD_MATRIX            =  100200
  CULLING                     =  100201
  SAMPLING_TOLERANCE          =  100203
  DISPLAY_MODE                =  100204
  PARAMETRIC_TOLERANCE        =  100202
  SAMPLING_METHOD             =  100205
  U_STEP                      =  100206
  V_STEP                      =  100207
  NURBS_MODE                  =  100160
  NURBS_MODE_EXT              =  100160
  NURBS_TESSELLATOR           =  100161
  NURBS_TESSELLATOR_EXT       =  100161
  NURBS_RENDERER              =  100162
  NURBS_RENDERER_EXT          =  100162
  OBJECT_PARAMETRIC_ERROR     =  100208
  OBJECT_PARAMETRIC_ERROR_EXT =  100208
  OBJECT_PATH_LENGTH          =  100209
  OBJECT_PATH_LENGTH_EXT      =  100209
  PATH_LENGTH                 =  100215
  PARAMETRIC_ERROR            =  100216
  DOMAIN_DISTANCE             =  100217
  MAP1_TRIM_2                 =  100210
  MAP1_TRIM_3                 =  100211
  POINT                       =  100010
  LINE                        =  100011
  FILL                        =  100012
  SILHOUETTE                  =  100013
  SMOOTH                      =  100000
  FLAT                        =  100001
  NONE                        =  100002
  OUTSIDE                     =  100020
  INSIDE                      =  100021
  TESS_BEGIN                  =  100100
  BEGIN_                      =  100100
  TESS_VERTEX                 =  100101
  VERTEX                      =  100101
  TESS_END                    =  100102
  END_                        =  100102
  TESS_ERROR                  =  100103
  TESS_EDGE_FLAG              =  100104
  EDGE_FLAG                   =  100104
  TESS_COMBINE                =  100105
  TESS_BEGIN_DATA             =  100106
  TESS_VERTEX_DATA            =  100107
  TESS_END_DATA               =  100108
  TESS_ERROR_DATA             =  100109
  TESS_EDGE_FLAG_DATA         =  100110
  TESS_COMBINE_DATA           =  100111
  CW                          =  100120
  CCW                         =  100121
  INTERIOR                    =  100122
  EXTERIOR                    =  100123
  UNKNOWN                     =  100124
  TESS_WINDING_RULE           =  100140
  TESS_BOUNDARY_ONLY          =  100141
  TESS_TOLERANCE              =  100142
  TESS_ERROR1                 =  100151
  TESS_ERROR2                 =  100152
  TESS_ERROR3                 =  100153
  TESS_ERROR4                 =  100154
  TESS_ERROR5                 =  100155
  TESS_ERROR6                 =  100156
  TESS_ERROR7                 =  100157
  TESS_ERROR8                 =  100158
  TESS_MISSING_BEGIN_POLYGON  =  100151
  TESS_MISSING_BEGIN_CONTOUR  =  100152
  TESS_MISSING_END_POLYGON    =  100153
  TESS_MISSING_END_CONTOUR    =  100154
  TESS_COORD_TOO_LARGE        =  100155
  TESS_NEED_COMBINE_CALLBACK  =  100156
  TESS_WINDING_ODD            =  100130
  TESS_WINDING_NONZERO        =  100131
  TESS_WINDING_POSITIVE       =  100132
  TESS_WINDING_NEGATIVE       =  100133
  TESS_WINDING_ABS_GEQ_TWO    =  100134
  TESS_MAX_COORD              = 1.0e150
  alias Nurbs = Void
  alias Quadric = Void
  alias Tesselator = Void

  fun begin_curve = "gluBeginCurve"(nurb : Nurbs*) : Void
  fun begin_polygon = "gluBeginPolygon"(tess : Tesselator*) : Void
  fun begin_surface = "gluBeginSurface"(nurb : Nurbs*) : Void
  fun begin_trim = "gluBeginTrim"(nurb : Nurbs*) : Void
  fun build1d_mipmap_levels = "gluBuild1DMipmapLevels"(target : UInt16, internal_format : Int16, width : Int16, format : UInt16, type : UInt16, level : Int16, base : Int16, max : Int16, data : Void*) : Int16
  fun build1d_mipmaps = "gluBuild1DMipmaps"(target : UInt16, internal_format : Int16, width : Int16, format : UInt16, type : UInt16, data : Void*) : Int16
  fun build2d_mipmap_levels = "gluBuild2DMipmapLevels"(target : UInt16, internal_format : Int16, width : Int16, height : Int16, format : UInt16, type : UInt16, level : Int16, base : Int16, max : Int16, data : Void*) : Int16
  fun build2d_mipmaps = "gluBuild2DMipmaps"(target : UInt16, internal_format : Int16, width : Int16, height : Int16, format : UInt16, type : UInt16, data : Void*) : Int16
  fun build3d_mipmap_levels = "gluBuild3DMipmapLevels"(target : UInt16, internal_format : Int16, width : Int16, height : Int16, depth : Int16, format : UInt16, type : UInt16, level : Int16, base : Int16, max : Int16, data : Void*) : Int16
  fun build3d_mipmaps = "gluBuild3DMipmaps"(target : UInt16, internal_format : Int16, width : Int16, height : Int16, depth : Int16, format : UInt16, type : UInt16, data : Void*) : Int16
  fun check_extension = "gluCheckExtension"(ext_name : Void*, ext_string : Void*) : UInt8
  fun cylinder = "gluCylinder"(quad : Quadric*, base : Float64, top : Float64, height : Float64, slices : Int16, stacks : Int16) : Void
  fun delete_nurbs_renderer = "gluDeleteNurbsRenderer"(nurb : Nurbs*) : Void
  fun delete_quadric = "gluDeleteQuadric"(quad : Quadric*) : Void
  fun delete_tess = "gluDeleteTess"(tess : Tesselator*) : Void
  fun disk = "gluDisk"(quad : Quadric*, inner : Float64, outer : Float64, slices : Int16, loops : Int16) : Void
  fun end_curve = "gluEndCurve"(nurb : Nurbs*) : Void
  fun end_polygon = "gluEndPolygon"(tess : Tesselator*) : Void
  fun end_surface = "gluEndSurface"(nurb : Nurbs*) : Void
  fun end_trim = "gluEndTrim"(nurb : Nurbs*) : Void
  fun error_string = "gluErrorString"(error : UInt16) : Void*
  fun get_nurbs_property = "gluGetNurbsProperty"(nurb : Nurbs*, property : UInt16, data : Void*) : Void
  fun get_string = "gluGetString"(name : UInt16) : Void*
  fun get_tess_property = "gluGetTessProperty"(tess : Tesselator*, which : UInt16, data : Void*) : Void
  fun load_sampling_matrices = "gluLoadSamplingMatrices"(nurb : Nurbs*, model : Void*, perspective : Void*, view : Void*) : Void
  fun look_at = "gluLookAt"(eye_x : Float64, eye_y : Float64, eye_z : Float64, center_x : Float64, center_y : Float64, center_z : Float64, up_x : Float64, up_y : Float64, up_z : Float64) : Void
  fun new_nurbs_renderer = "gluNewNurbsRenderer" : Nurbs*
  fun new_quadric = "gluNewQuadric" : Quadric*
  fun new_tess = "gluNewTess" : Tesselator*
  fun next_contour = "gluNextContour"(tess : Tesselator*, type : UInt16) : Void
  fun nurbs_callback = "gluNurbsCallback"(nurb : Nurbs*, which : UInt16, call_back_func : Void*) : Void
  fun nurbs_callback_data = "gluNurbsCallbackData"(nurb : Nurbs*, user_data : Void*) : Void
  fun nurbs_callback_data_ext = "gluNurbsCallbackDataEXT"(nurb : Nurbs*, user_data : Void*) : Void
  fun nurbs_curve = "gluNurbsCurve"(nurb : Nurbs*, knot_count : Int16, knots : Void*, stride : Int16, control : Void*, order : Int16, type : UInt16) : Void
  fun nurbs_property = "gluNurbsProperty"(nurb : Nurbs*, property : UInt16, value : Float32) : Void
  fun nurbs_surface = "gluNurbsSurface"(nurb : Nurbs*, s_knot_count : Int16, s_knots : Void*, t_knot_count : Int16, t_knots : Void*, s_stride : Int16, t_stride : Int16, control : Void*, s_order : Int16, t_order : Int16, type : UInt16) : Void
  fun ortho2d = "gluOrtho2D"(left : Float64, right : Float64, bottom : Float64, top : Float64) : Void
  fun partial_disk = "gluPartialDisk"(quad : Quadric*, inner : Float64, outer : Float64, slices : Int16, loops : Int16, start : Float64, sweep : Float64) : Void
  fun perspective = "gluPerspective"(fovy : Float64, aspect : Float64, z_near : Float64, z_far : Float64) : Void
  fun pick_matrix = "gluPickMatrix"(x : Float64, y : Float64, del_x : Float64, del_y : Float64, viewport : Void*) : Void
  fun project = "gluProject"(obj_x : Float64, obj_y : Float64, obj_z : Float64, model : Void*, proj : Void*, view : Void*, win_x : Void*, win_y : Void*, win_z : Void*) : Int16
  fun pwl_curve = "gluPwlCurve"(nurb : Nurbs*, count : Int16, data : Void*, stride : Int16, type : UInt16) : Void
  fun quadric_callback = "gluQuadricCallback"(quad : Quadric*, which : UInt16, call_back_func : Void*) : Void
  fun quadric_draw_style = "gluQuadricDrawStyle"(quad : Quadric*, draw : UInt16) : Void
  fun quadric_normals = "gluQuadricNormals"(quad : Quadric*, normal : UInt16) : Void
  fun quadric_orientation = "gluQuadricOrientation"(quad : Quadric*, orientation : UInt16) : Void
  fun quadric_texture = "gluQuadricTexture"(quad : Quadric*, texture : UInt8) : Void
  fun scale_image = "gluScaleImage"(format : UInt16, w_in : Int16, h_in : Int16, type_in : UInt16, data_in : Void*, w_out : Int16, h_out : Int16, type_out : UInt16, data_out : Void*) : Int16
  fun sphere = "gluSphere"(quad : Quadric*, radius : Float64, slices : Int16, stacks : Int16) : Void
  fun tess_begin_contour = "gluTessBeginContour"(tess : Tesselator*) : Void
  fun tess_begin_polygon = "gluTessBeginPolygon"(tess : Tesselator*, data : Void*) : Void
  fun tess_callback = "gluTessCallback"(tess : Tesselator*, which : UInt16, call_back_func : Void*) : Void
  fun tess_end_contour = "gluTessEndContour"(tess : Tesselator*) : Void
  fun tess_end_polygon = "gluTessEndPolygon"(tess : Tesselator*) : Void
  fun tess_normal = "gluTessNormal"(tess : Tesselator*, value_x : Float64, value_y : Float64, value_z : Float64) : Void
  fun tess_property = "gluTessProperty"(tess : Tesselator*, which : UInt16, data : Float64) : Void
  fun tess_vertex = "gluTessVertex"(tess : Tesselator*, location : Void*, data : Void*) : Void
  fun un_project = "gluUnProject"(win_x : Float64, win_y : Float64, win_z : Float64, model : Void*, proj : Void*, view : Void*, obj_x : Void*, obj_y : Void*, obj_z : Void*) : Int16
  fun un_project4 = "gluUnProject4"(win_x : Float64, win_y : Float64, win_z : Float64, clip_w : Float64, model : Void*, proj : Void*, view : Void*, near_val : Float64, far_val : Float64, obj_x : Void*, obj_y : Void*, obj_z : Void*, obj_w : Void*) : Int16
end
